CREATE TABLE IF NOT EXISTS usuarios(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    usuario TEXT NOT NULL UNIQUE,
    senha_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS semaforos(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    localizacao TEXT NOT NULL,
    estado TEXT NOT NULL,
    tempo INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS postes(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    localizacao TEXT NOT NULL,
    estado INTEGER NOT NULL,
    atomatico INTEGER NOT NULL DEFAULT 0
);